### ISSUE TITLE
Parser also matches hostname 

### ISSUE THREAD

**Issue by network-shark** [dmulyalin/salt-ttp#1]
Hello @dmulyalin ,

thanks for writing this salt plugin. I tried to use it , but I don't get the expected output. 

First I hardcoded everthing in my custom module and use ttp . I got it working and the output was working as expected. Then I remembered that you created a PR for salt , but it seems you just created an extension instead. 

template.txt
```
<group>
Port      Mode         Encapsulation  Status        Native_vlan  {{ _headers_ }}
</group>
```
command run against cisco device
```
show interfaces trunk
```

output of show interfaces trunk 
```
XXXXXXXXXXXXXXXXXXX#show interfaces trunk

Port        Mode             Encapsulation  Status        Native vlan
Gi0/1/0     on               802.1q         trunking      1

Port        Vlans allowed on trunk
Gi0/1/0     1,8,999,1002-1005

Port        Vlans allowed and active in management domain
Gi0/1/0     1,8,999

Port        Vlans in spanning tree forwarding state and not pruned
Gi0/1/0     1,8,999
```

salt returns
```
XXXXXXXXXXXXXXXXXXX:
    |_
      |_
        |_
          ----------
          Encapsulation:
              w interfaces tr
          Mode:
              xxxxxxxxx#sho
          Native_vlan:
          Port:
              xxxxxxxxxx
          Status:
              unk
        |_
          ----------
          Encapsulation:
              802.1q
          Mode:
              on
          Native_vlan:
              1
          Port:
              Gi0/1/0
          Status:
              trunking
```

I don't know why , but it also matches on the show interface trunk line. 

Hardcoded version 

```
    template = '''
<group>
Port      Mode         Encapsulation  Status        Native_vlan  {{ _headers_ }}
</group>
'''


#
    cmd = 'show interfaces trunk'
    ret = __salt__['net.cli'](
            cmd
            )


    parser = ttp(ret['out'][cmd], template)
    parser.parse()
    log.debug(parser.result(structure="flat_list"))
    return(parser.result(structure="flat_list"))
```

```
XXXXXXXXXXXXX:
    |_
      ----------
      Encapsulation:
          802.1q
      Mode:
          on
      Native_vlan:
          1
      Port:
          Gi0/1/0
      Status:
          trunking
```

**Comment by dmulyalin** [comment]
Hi, Salt-ttp reconstructs device prompt for gethostname to work, headers indicator matches it, need to use group filtering function https://ttp.readthedocs.io/en/latest/Groups/Functions.html#exclude-val to exclude show interface trunk from matches.

**Comment by network-shark** [comment]
Does ttp need the variable $gethostname to return the dict ? Would't it be possible to use grains for the hostname or does all the output is returned by ttp even the hostname?

**Comment by dmulyalin** [comment]
Adding hostname to output from devices is only required for `gethostname` to work, no other dependencies, that is done like that because it is not feasible to source device's hostname from grains or pillar for all use cases, for example - parsing output produced by Nornir Salt proxy minion.

**Comment by network-shark** [comment]
Ok , thanks for the explanation 👍
